apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencnapp-api
spec:
  replicas: 1
  selector:
    matchLabels: { app: opencnapp-api }
  template:
    metadata:
      labels: { app: opencnapp-api }
    spec:
      containers:
        - name: api
          image: {{ .Values.image.api }}
          ports:
            - containerPort: 8000
