apiVersion: v1
kind: Secret
metadata:
  name: opencnapp-env
type: Opaque
stringData:
  SECRET_KEY: change-me
  DATABASE_URL: postgresql://opencnapp:opencnapp@opencnapp-postgres:5432/opencnapp
  REDIS_URL: redis://opencnapp-redis:6379/0
